version: 2.1
orbs:
  node: circleci/node@5.2.0
executors:
  default:
    docker:
      - image: cimg/node:21.7.1
jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - node/install-packages
      - run:
          name: Build
          command: npm run build
  test:
    executor:
      name: default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Test
          command: npm run test
  prettier:
    executor:
      name: default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Prettier
          command: npm run prettier -- --check
workflows:
  test:
    jobs:
      - build
      - test
      - prettier
